---

- name: Get the username running the deploy
  local_action: command whoami
  register: running_user_cmd

- name: Set username fact
  set_fact:
    running_user: "{{ running_user_cmd.stdout }}"

- name: Install base packages
  become: yes
  apt:
    name:
      - curl
      - git
      - htop
      - lm-sensors
      - ntp
      - python-pip
      - rsync
      - vim
      - zsh
    state: present

- name: Enable base services
  become: yes
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - ntp

- name: Enable modules
  become: yes
  lineinfile:
    path: /etc/modules
    line: "{{ item }}"
  with_items:
    - 8021q
    - bonding

- name: Check out linux setup repo for update and kernel scripts
  git:
    repo: https://github.com/mnewswanger/linux-setup.git
    dest: ~/linux-setup
