---

- name: Install base packages
  apt:
    name:
      - ntp
      - rsync
      - vim
      - zsh
    state: present

- name: Enable base services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - ntp
