---

- name: Increase file watch limit
  become: yes
  copy:
    dest: /etc/sysctl.d/file-watch-limits.conf
    src: file-watch-limits.conf
    force: no

- name: Create backup user group
  become: yes
  group:
    name: backup-users

- name: Create backup backup backup users
  become: yes
  user:
    name: "{{ item }}"
    group: backup-users
    generate_ssh_key: yes
  with_items:
    - do-backups
    - marie-backups
    - mike-backups

- name: Create digital ocean backup folders
  become: yes
  file:
    dest: "{{ item }}"
    owner: do-backups
    group: backup-users
    state: directory
  with_items:
    - /mnt/backups/digital-ocean/do-webserver01/database
    - /mnt/backups/digital-ocean/do-webserver01/websites

- name: Create mike backup targets
  become: yes
  file:
    dest: "{{ item }}"
    owner: mike-backups
    group: backup-users
    state: directory
  with_items:
    - /mnt/backups/computers/war-machine.local/mike/

- name: Create marie backup targets
  become: yes
  file:
    dest: "{{ item }}"
    owner: marie-backups
    group: backup-users
    state: directory
  with_items:
    - /mnt/backups/computers/mf-m4600/marie

- name: Create backup pull jobs
  become: yes
  copy:
    src: digital-ocean-backups
    dest: /etc/cron.d/digital-ocean-backups
